
import type { Language } from './types';

export const texts: Record<Language, any> = {
  en: {
    appName: "Abhawa",
    weather: "Weather",
    prayerTimes: "Prayer Times",
    accuweather: "AccuWeather",
    searchPlaceholder: "Search for a city...",
    search: "Search",
    loading: "Fetching the latest data...",
    currentWeather: "Current Weather",
    feelsLike: "Feels Like",
    humidity: "Humidity",
    wind: "Wind",
    pressure: "Pressure",
    uvIndex: "UV Index",
    airQuality: "Air Quality",
    sunrise: "Sunrise",
    sunset: "Sunset",
    gregorian: "Gregorian",
    bengali: "Bengali",
    hijri: "Hijri",
    date: "Date",
    day: "Day",
    minuteCast: "Minute Cast",
    hourlyForecast: "Today's Hourly Forecast",
    todaysSummary: "Today's Summary",
    tomorrowsForecast: "Tomorrow's Forecast",
    tomorrowsSummary: "Tomorrow's Summary",
    weeklyForecast: "7-Day Forecast",
    weeklySummary: "Weekly Summary",
    prayerSchedule: "Prayer Schedule (Hanafi)",
    waqt: "Waqt",
    start: "Start",
    end: "End",
    fajr: "Fajr",
    dhuhr: "Dhuhr",
    asr: "Asr",
    maghrib: "Maghrib",
    isha: "Isha",
    initialSearchTitle: "Welcome to Abhawa",
    initialSearchPrompt: "Find weather for your location",
    useCurrentLocation: "Use my current location",
    or: "or",
    footerCredit: "Developed By Muhammad Aslam Uddin (M.A.U)",
    sourcesTitle: "Data Sources",
    error: {
      generic: "An error occurred. Please try again.",
      noData: "No data available. Please try a different location.",
      location: "Could not get your location. Please check browser permissions and try again.",
      geolocationFailed: "Could not get your location. Showing weather for Kadakati by default."
    }
  },
  bn: {
    appName: "আবহাওয়া",
    weather: "আবহাওয়া",
    prayerTimes: "নামাজের সময়সূচী",
    accuweather: "অ্যাকুওয়েদার",
    searchPlaceholder: "শহর খুঁজুন...",
    search: "অনুসন্ধান",
    loading: "সর্বশেষ তথ্য আনা হচ্ছে...",
    currentWeather: "বর্তমান আবহাওয়া",
    feelsLike: "অনুভূত হচ্ছে",
    humidity: "আর্দ্রতা",
    wind: "বাতাস",
    pressure: "চাপ",
    uvIndex: "ইউভি ইনডেক্স",
    airQuality: "বাতাসের অবস্থা",
    sunrise: "সূর্যোদয়",
    sunset: "সূর্যাস্ত",
    gregorian: "ইংরেজি",
    bengali: "বাংলা",
    hijri: "হিজরি",
    date: "তারিখ",
    day: "দিন",
    minuteCast: "মিনিট কাস্ট",
    hourlyForecast: "আজকের ঘণ্টায় ঘণ্টায় পূর্বাভাস",
    todaysSummary: "আজকের সারসংক্ষেপ",
    tomorrowsForecast: "আগামীকালের পূর্বাভাস",
    tomorrowsSummary: "আগামীকালের সারসংক্ষেপ",
    weeklyForecast: "৭-দিনের পূর্বাভাস",
    weeklySummary: "সাপ্তাহিক সারসংক্ষেপ",
    prayerSchedule: "নামাজের সময়সূচী (হানাফী)",
    waqt: "ওয়াক্ত",
    start: "শুরু",
    end: "শেষ",
    fajr: "ফজর",
    dhuhr: "যোহর",
    asr: "আসর",
    maghrib: "মাগরিব",
    isha: "এশা",
    initialSearchTitle: "আবহাওয়াতে স্বাগতম",
    initialSearchPrompt: "আপনার এলাকার আবহাওয়া খুঁজুন",
    useCurrentLocation: "আমার বর্তমান অবস্থান ব্যবহার করুন",
    or: "অথবা",
    footerCredit: "ডেভেলপ করেছেন মুহাম্মদ আসলাম উদ্দিন (এম.এ.ইউ)",
    sourcesTitle: "তথ্যের উৎস",
    error: {
      generic: "একটি ত্রুটি ঘটেছে। আবার চেষ্টা করুন.",
      noData: "কোনো ডেটা পাওয়া যায়নি। অনুগ্রহ করে অন্য একটি অবস্থান চেষ্টা করুন।",
      location: "আপনার অবস্থান পাওয়া যায়নি। অনুগ্রহ করে ব্রাউজারের অনুমতি পরীক্ষা করে আবার চেষ্টা করুন।",
      geolocationFailed: "আপনার অবস্থান পাওয়া যায়নি। ডিফল্ট হিসেবে কদাকাটির আবহাওয়া দেখানো হচ্ছে।"
    }
  }
};